services:

  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://fact_user:fact_pass@db:5432/facturacio_db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fact_user
      - POSTGRES_PASSWORD=fact_pass
      - POSTGRES_DB=facturacio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: